_WaveInit	proto	dwNumber1:dword,dwNumber2:dword,dwNumber3:dword,dwNumber4:dword,dwNumber5:dword
_WaveDropStone	proto	dwNumber1:dword,dwNumber2:dword,dwNumber3:dword,dwNumber4:dword,dwNumber5:dword
_WaveEffect	proto	dwNumber1:dword,dwNumber2:dword,dwNumber3:dword,dwNumber4:dword,dwNumber5:dword
_WaveUpdateFrame proto	dwNumber1:dword,dwNumber2:dword,dwNumber3:dword
_WaveFree	proto	dwNumber1:dword