
 IDC_MYICON                      EQU		2
 IDD_PEINFO_EXAMPLE_DIALOG       EQU		102
 IDD_ABOUTBOX                    EQU		103
 IDS_APP_TITLE                   EQU		103
 IDM_ABOUT                       EQU		104
 IDM_EXIT                        EQU		105
 IDS_HELLO                       EQU		106
 IDI_PEINFO_EXAMPLE              EQU		107
 IDI_SMALL                       EQU		108
 IDC_PEINFO_EXAMPLE              EQU		109
 IDR_MAINFRAME                   EQU		128
 IDD_MAIN_DLG                    EQU		129
 IDD_SHT_DLG                     EQU		130
 IDD_DATADIR_DLG                 EQU		131
 IDD_EXPORT_DLG                  EQU		132
 IDD_IMPORT_DLG                  EQU		133
 IDC_BUTTON1                     EQU		1000
;----------------------------------------------------------
;16个数据目录表的属性,RVA由1001到1016;SIZE由1017到1032
 IDC_ABOUTBTN                    EQU		1001

 ID_RVA_START			 EQU		1001
 IDC_EDIT_DD_RVA_EXPORT          EQU		1001
 IDC_EXIT                        EQU		1002
 IDC_EDIT_DD_RVA_IMPORT          EQU		1002
 IDC_EDIT_DD_RVA_RES             EQU		1003
 IDC_EDIT_EXPDIR_DLLNAME         EQU		1003
 IDC_EDIT_DD_RVA_EXCEPTION       EQU		1004
 IDC_EDIT_DD_RVA_SECURITY        EQU		1005
 IDC_SECTIONLIST                 EQU		1006
 IDC_EDIT_DD_RVA_RELOC           EQU		1006
 IDC_EDIT_DD_RVA_DEBUG           EQU		1007
 IDC_EDIT_DD_RVA_COPYRIGHT       EQU		1008
 IDC_EDIT_DD_RVA_GP              EQU		1009
 IDC_EDIT_DD_RVA_TLS             EQU		1010
 IDC_EDIT_DD_RVA_LOADCONFIG      EQU		1011
 IDC_EDIT_FH_MACHINE             EQU		1012
 IDC_EDIT_DD_RVA_IAT             EQU		1012
 IDC_EDIT_FH_NUMOFSECTIONS       EQU		1013
 IDC_EDIT_DD_RVA_BOUND           EQU		1013
 IDC_EDIT_FH_TDS                 EQU		1014
 IDC_EDIT_DD_RVA_COM             EQU		1014
 IDC_EDIT_FH_PTSYMBOL            EQU		1015
 IDC_EDIT_DD_RVA_DELAYIMPORT     EQU		1015
 IDC_EDIT_FH_NUMOFSYM            EQU		1016
 IDC_EDIT_DD_RVA_NOUSE           EQU		1016
 IDC_EDIT_FH_SIZEOFOH            EQU		1017

 ID_SIZE_START			 EQU		1017
 IDC_EDIT_DD_SIZE_EXPORT         EQU		1017
 IDC_EDIT_FH_CHARACTERISTICS     EQU		1018
 IDC_EDIT_DD_SIZE_IMPORT         EQU		1018
 IDC_EDIT_DD_SZIE_RES            EQU		1019
 IDC_EDIT_DD_SZIE_EXCEPTION      EQU		1020
 IDC_EDIT_DD_SIZE_SECURITY       EQU		1021
 IDC_EDIT_DD_SIZE_RELOC          EQU		1022
 IDC_EDIT_DD_SIZE_DEBUG          EQU		1023
 IDC_SHOWSHT                     EQU		1024
 IDC_EDIT_DD_SIZE_COPYRIGHT      EQU		1024
 IDC_SHOWDATADIR                 EQU		1025
 IDC_EDIT_DD_SIZE_GP             EQU		1025
 IDC_EDIT_DD_SIZE_TLS            EQU		1026
 IDC_EDIT_DD_SIZE_LOADCONFIG     EQU		1027
 IDC_EDIT_DD_SIZE_IAT            EQU		1028
 IDC_EDIT_DD_SIZE_BOUND          EQU		1029
 IDC_EDIT_DD_SIZE_COM            EQU		1030
 IDC_EDIT_DD_SIZE_DELAYIMPORT    EQU		1031
 IDC_EDIT_DD_SIZE_NOUSE          EQU		1032
;----------------------------------------------------------
 IDC_SHOWEXPORT_BTN              EQU		1033
 IDC_OK                          EQU		1034
 IDC_EDIT_EXPDIR_CHARACTERISTICS EQU		1035
 IDC_EDIT_EXPDIR_TDS             EQU		1036
 
 IDC_EDIT_EXPDIR_BASE            EQU		1037
 
 IDC_EDIT_EXPDIR_NAME            EQU		1038
 
 IDC_EDIT_EXPDIR_NUMOFFUNCS      EQU		1039
 
 IDC_EDIT_EXPDIR_NUMOFNAMES      EQU		1040
 
 IDC_EDIT_EXPDIR_ADDROFFUNCS     EQU		1041
 
 IDC_EDIT_EXPDIR_ADDROFNAMES     EQU		1042
 
 IDC_EDIT_EXPDIR_ADDROFNAMEORD   EQU		1043
 IDC_EXPORT_LIST                 EQU		1044
 
 IDC_IMPORT_LIST                 EQU		1045
 
 IDC_IMPORTFUNCTIONS_LIST        EQU		1046
 IDC_SHOWIMPORT_BTN              EQU		1047
 IDC_OPEN_BTN                    EQU		1048
 IDC_FILEPATH_EDIT               EQU		1049
 IDC_SHOWOH                      EQU		1060
 IDC_EDIT_OH_EP                  EQU		1062
 IDC_EDIT_OH_IMAGEBASE           EQU		1063
 IDC_EDIT_OH_CODEBASE            EQU		1064
 IDC_EDIT_OH_DATABASE            EQU		1065
 IDC_EDIT_OH_IMAGESIZE           EQU		1066
 IDC_EDIT_OH_HEADERSIZE          EQU		1067
 IDC_EDIT_OH_SECTIONALIGN        EQU		1068
 IDC_EDIT_OH_FILEALIGN           EQU		1069
 IDC_EDIT_OH_SUBSYSTEM           EQU		1070
 IDC_EDIT_OH_CHECKSUM            EQU		1071
 IDC_EDIT_OH_DLLFLAGS            EQU		1072
 IDC_STATIC                      EQU		-1


